### PR TITLE
When requesting mermaid graph, ask for text/x-mermaid content-type.

### PR DESCRIPTION
**Pull request by rixed**
Ask for text/x-mermaid content-type when requesting the mermaid graph.

Should not change much to simple server, and allow more evolved servers to adapt output according to Accept header rather than the ressource name, which makes more sense.
For instance, on my service the same /graph resource can return either graphviz or mermaid format according to requested content-type.

### CODE REVIEW

**Comment by ben-turner** [comment]
I'm wondering if it would be better to use `Accept: text/x-mermaid,text/plain` or even `Accept: text/x-mermaid,text/plain;q=0.9` so as to not cause a 406 from dumber servers, but still show that we want mermaid syntax? Another solution could also be to re-try the request with `Accept: text/plain` if we get a 406 but that's kinda gross.

**Comment by rixed** [comment]
I was a bit annoyed by this as well and hadn't thought about asking also for text/plain.
I like your proposal of asking also for text/plain with a lower q. Or why not go the full route and ask for: `text/x-mermaid,*/*;q=0.9` ?

**Comment by ben-turner** [comment]
D) all of the above? `Accept: text/x-mermaid,text/plain;q=0.9,*/*;q=0.8`

**Comment by rixed** [comment]
SGTM. Will update this PR.

**Comment by rixed** [comment]
Also, rebased.

**Pull request merged**
