### PR TITLE
Fixes for rendering values on diagram

### LINKED ISSUE #67: Current git version seems broken
No metrics are displayed when using latest version from git. 
I would love to try to fix this, but it might be easier with a little insight on why it might have stopped working ?
@jdbranham I know you most likely are busy with other stuff, but maybe you can somehow help me and/or other developers with continuing your great work ?

### PR DESCRIPTION
**Pull request by briangann**
This fixes the bugs causing values to not render for nodes (only link values were being rendered)

There were a couple of bugs introduced with recent commits:

1) handling of "this" and "_this" in the callback when using remote mermaid diagram source vs local diagram definition, this prevented the callback from working
2) render has to be called at the end of onDataReceived, as well as setting svgData (used to update values) - this caused the values to not render, but the diagram did render (it's a two-pass process)

fixes #67 #56

### CODE REVIEW

**Comment by briangann** [comment]
Added new feature to address #66
Also added refresh() calls so editor changes are reflected when you leave a field (on-blur)

**Comment by NicolaiPetri** [comment]
This seems to fix some issues. But I still have a problem with the following error 👍 
`TypeError: Cannot read property 'replace' of undefined
    at DiagramCtrl.replaceMetricCharacters (https://grafana.supersecrethost.com/public/plugins/jdbranham-diagram-panel/diagramControl.js:224:43)
    at DiagramCtrl.seriesHandler (https://grafana.supersecrethost.com/public/plugins/jdbranham-diagram-panel/diagramControl.js:242:30)
    at Array.map (<anonymous>)
    at DiagramCtrl.onDataReceived (https://grafana.supersecrethost.com/public/plugins/jdbranham-diagram-panel/diagramControl.js:211:36)
    at o.emit (https://grafana.supersecrethost.com/public/build/vendor.2305a8e1d478628b1297.js:15:520749)
    at t.emit (https://grafana.supersecrethost.com/public/build/app.8849fc3d424a44caa6fc.js:1:29207)
    at DiagramCtrl.e.handleQueryResult (https://grafana.supersecrethost.com/public/build/0.7d03bf00820ec00459ae.js:7:19860)
    at u (https://grafana.supersecrethost.com/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
    at https://grafana.supersecrethost.com/public/build/vendor.2305a8e1d478628b1297.js:43:69127
    at f.$digest (https://grafana.supersecrethost.com/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
`
I don't know if it's related to me using both azure monitor, prometheus and composites on same diagram

**Comment by briangann** [comment]
I'll add in a test for "metricName" so it won't throw errors on bad data.

This happens when a datasource sends a time series that has no "target" (which is likely a bug in the datasource)

**Comment by NicolaiPetri** [comment]
Thanks.
I can see this is a "common" problem with Azure Monitor datasource and Application Insights. If there is no data for requested period it apparently doesn't handle it well.
I'll try to bug maintainers of that datasource too :)

Once again, thanks a million for the help.

**Comment by briangann** [comment]
Here's what it will do once this is committed - when a metric is received with an invalid target (anything other than a string), the series will have an alias injected with a new name.

Throwing away the data seems like it just masks the underlying problem.  Having a hint from the panel helps.


image

**Pull request merged**
