### PR TITLE
replace variables in diag url

### PR DESCRIPTION
**Pull request by patjlm**
I was actually not able to test locally, but it seems to me this should be fine, right ?

### CODE REVIEW

**Comment by ahmadalli** [comment]
@jdbranham Can you please take a look into this PR?

**Comment by jdbranham** [comment]
Hi there!
I'll pull this locally to test, and merge up

**Comment by ahmadalli** [comment]
@jdbranham Thank you! Would it be possible to also have a new release of the plugin?

**Comment by jdbranham** [comment]
Good call @ahmadalli 

I attempted to release v1.9.0 , but it looks like the process may have changed since we last released.  
We'll need to dig into this...  
https://github.com/jdbranham/grafana-diagram/actions/runs/7875286121

**Comment by ahmadalli** [comment]
@jdbranham Maybe `npx @grafana/create-plugin@latest update` fixes this?

https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/README.md#update-your-plugin-build-config

**Comment by tolzhabayev** [comment]
Hey @jdbranham,

there is a PR that updates the workflows https://github.com/jdbranham/grafana-diagram/pull/250

In your case it fails on the sign plugin action because it is running `yarn sign` which then calls `npx` (which is part of `npm`) - so you should adjust the workflow to either do `npm run sign` or just run the command directly. Also node version that you are using in the workflow is quite outdated, it works best with node 20.

You can see the latest workflows we provide by default if you run `npx @grafana/create-plugin@latest` in an empty folder (not inside of this project) and go through the scaffolding process - then check out the .github folder in the newly created project. It should contain all the latest workflows.

Also here are the docs on tokens that are used for plugin signing https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin

**Comment by jdbranham** [comment]
Thanks @tolzhabayev @ahmadalli @patjlm 

I've been swamped at work for months! - I'll get release out asap.

**Comment by ahmadalli** [comment]
Thank you @jdbranham for your time and effort. It seems like the sign process has a new dependency now: https://github.com/jdbranham/grafana-diagram/actions/runs/7892458703/job/21538967272#step:10:1

**Comment by ahmadalli** [comment]
@jdbranham Actually it seems like only the release is missing and Github action run for v1.10.2 was successful

**Pull request merged**
