### PR TITLE
dynamic diagram feature using a separate service to provide graphDefinitions

### PR DESCRIPTION
**Pull request by cproinger**
with my limited knowledge about grafana-plugins and the technologies in use i achieved a simple solution to issue #49 by making an ajax request to a service that responds with mermaid-graph-definitions. templating on the provided URL also works.

### CODE REVIEW

**Comment by cproinger** [comment]
i found a problem when i use the All-option. i will see if i can fix that

**Comment by rixed** [comment]
What's the status on this? I think I have the exact same need and would like to see the graph received from some configurable URL.
@cproinger : are you still working on this?

**Comment by rixed** [comment]
OK I rebased myself.
Had to merge those 3 commits into a single one since you guys weren't using the same newline chars which made the whole thing conflicting, so having a single patch was easier to handle.
I tested the thing and it works for me. Will open another PR (still @cproinger stays the author of course, that's his bugs not mine :-D)

**Comment by jdbranham** [comment]
Merged in pr #58

**Pull request closed without merging**
